name: Generate Dart Documentation

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0

      - name: Git Setup
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git branch --all
          git switch --track origin/documentation
          git reset --hard origin/main

      - name: Install Dart
        uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get

      - name: Analyze Dart code
        run: dart analyze --fatal-infos
        
      - name: Output error
        if: failure()
        run: echo "::error The code or is missing documentation. Run flutter analyze --dartdocs"

      - name: Generate documentation
        run: dart doc --output=docs

      - name: Commit and push files
        run: |
          cd docs
          cd ..
          git status
          git stage --force docs
          git commit -a -m "Generated documentation"
          git push --force      
